/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto.views;

import com.mycompany.projeto.dao.ProdutoDAO;
import com.mycompany.projeto.models.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class TelaProdutos extends javax.swing.JFrame {

    Produto objAlterar = null;
    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGuiasProduto = new javax.swing.JTabbedPane();
        pnlCadastroProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIDProduto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoProdutoCadastro = new javax.swing.JTextField();
        txtNomeProdutoCadastro = new javax.swing.JTextField();
        txtValorProdutoCadastro = new javax.swing.JTextField();
        txtQtdProdutoCadastro = new javax.swing.JTextField();
        btnConfirmarCadastroProduto = new javax.swing.JButton();
        btnCancelarCadastroProduto = new javax.swing.JButton();
        pnlConsultaProduto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        btnPesquisarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Quantidade:");

        jLabel6.setText("Código:");

        txtValorProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProdutoCadastroActionPerformed(evt);
            }
        });

        btnConfirmarCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_sim.png"))); // NOI18N
        btnConfirmarCadastroProduto.setText("Confirmar");
        btnConfirmarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCadastroProdutoActionPerformed(evt);
            }
        });

        btnCancelarCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_nao.png"))); // NOI18N
        btnCancelarCadastroProduto.setText("Cancelar");
        btnCancelarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroProdutoLayout = new javax.swing.GroupLayout(pnlCadastroProduto);
        pnlCadastroProduto.setLayout(pnlCadastroProdutoLayout);
        pnlCadastroProdutoLayout.setHorizontalGroup(
            pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(btnConfirmarCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnCancelarCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigoProdutoCadastro))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtQtdProdutoCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                    .addComponent(txtValorProdutoCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeProdutoCadastro))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCadastroProdutoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarCadastroProduto, btnConfirmarCadastroProduto});

        pnlCadastroProdutoLayout.setVerticalGroup(
            pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIDProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQtdProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCadastroProduto)
                    .addComponent(btnCancelarCadastroProduto))
                .addContainerGap())
        );

        pnlGuiasProduto.addTab("Cadastrar", pnlCadastroProduto);

        jLabel5.setText("Nome:");

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_lupa.png"))); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Valor", "Qnt"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_adicionar.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_lapis.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_nao.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaProdutoLayout = new javax.swing.GroupLayout(pnlConsultaProduto);
        pnlConsultaProduto.setLayout(pnlConsultaProdutoLayout);
        pnlConsultaProdutoLayout.setHorizontalGroup(
            pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConsultaProdutoLayout.setVerticalGroup(
            pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );

        pnlGuiasProduto.addTab("Consultar", pnlConsultaProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasProduto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasProduto)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCadastroProdutoActionPerformed

    private void txtValorProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProdutoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProdutoCadastroActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        String nomePesquisa = txtNomeProduto.getText().trim();
        ArrayList<Produto> lista = ProdutoDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
        modeloTabela.setRowCount(0);

        if (!nomePesquisa.isEmpty()) {
            boolean encontrou = false;
            for (Produto item : lista) {
                if (item.getNomeProduto().toLowerCase().contains(nomePesquisa.toLowerCase())) {
                    modeloTabela.addRow(new String[]{
                        String.valueOf(item.getIdProduto()),
                        String.valueOf(item.getCodProduto()),
                        item.getNomeProduto(),
                        String.valueOf(item.getValorProduto()),
                        String.valueOf(item.getQtdProduto())
                    });
                    encontrou = true;
                }
            }
            if (!encontrou) {
                JOptionPane.showMessageDialog(rootPane, "Nenhum produto encontrado com o nome informado!");
            }
        } else {
            for (Produto item : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(item.getIdProduto()),
                    String.valueOf(item.getCodProduto()),
                    item.getNomeProduto(),
                    String.valueOf(item.getValorProduto()),
                    String.valueOf(item.getQtdProduto())
                });
            }
        }
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        DefaultTableModel modeloClientes = (DefaultTableModel) tblProdutos.getModel();
        int linhaSelecionada = tblProdutos.getSelectedRow();
        if (linhaSelecionada >=0){
            int id = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 0).toString());
            int codProduto = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 1).toString());
            String nomeProduto = modeloClientes.getValueAt(linhaSelecionada, 2).toString();
            float valorProduto = Float.parseFloat(modeloClientes.getValueAt(linhaSelecionada, 3).toString());
            int qtdProduto = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 4).toString());
            
            objAlterar = new Produto(id, codProduto, nomeProduto, qtdProduto, valorProduto);
            
            pnlGuiasProduto.setSelectedIndex(0);
            lblIDProduto.setText(String.valueOf(objAlterar.getIdProduto()));
            txtCodigoProdutoCadastro.setText(String.valueOf(objAlterar.getCodProduto()));
            txtValorProdutoCadastro.setText(String.valueOf(objAlterar.getValorProduto()));
            txtQtdProdutoCadastro.setText(String.valueOf(objAlterar.getQtdProduto()));
            txtNomeProdutoCadastro.setText(objAlterar.getNomeProduto());
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela!");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tblProdutos.getSelectedRow();
        if(linhaSelecionada>=0){
            DefaultTableModel modeloTabela = (DefaultTableModel)tblProdutos.getModel();
            int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            boolean retorno = ProdutoDAO.excluir(idExcluir);
            if(retorno){
                JOptionPane.showMessageDialog(rootPane, "Produto deletado com sucesso!");
                atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não foi possível deletar o produto!");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConfirmarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCadastroProdutoActionPerformed
        if(objAlterar != null){
            int codProduto = Integer.parseInt(txtCodigoProdutoCadastro.getText());
            String nomeProduto = txtNomeProdutoCadastro.getText();
            int qtdProduto = Integer.parseInt(txtQtdProdutoCadastro.getText());
            float valorProduto = Float.parseFloat(txtValorProdutoCadastro.getText());
            int idProduto = Integer.parseInt(lblIDProduto.getText());
            
            objAlterar.setIdProduto(idProduto);
            objAlterar.setNomeProduto(nomeProduto);
            objAlterar.setQtdProduto(qtdProduto);
            objAlterar.setValorProduto(valorProduto);
            objAlterar.setCodProduto(codProduto);
            
            boolean retornoAlteracao = ProdutoDAO.alterar(objAlterar);
            if(retornoAlteracao){
                JOptionPane.showMessageDialog(rootPane, "Sucesso ao alterar");
                objAlterar = null;
                txtNomeProdutoCadastro.setText("");
                txtCodigoProdutoCadastro.setText("");
                txtValorProdutoCadastro.setText("");
                txtQtdProdutoCadastro.setText("");
                lblIDProduto.setText("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao alterar");
            }
        }else{
            int codProduto = Integer.parseInt(txtCodigoProdutoCadastro.getText());
            String nomeProduto = txtNomeProdutoCadastro.getText();
            int qtdProduto = Integer.parseInt(txtQtdProdutoCadastro.getText());
            float valorProduto = Float.parseFloat(txtValorProdutoCadastro.getText());
        
        Produto objCadastrar = new Produto(codProduto, nomeProduto, qtdProduto, valorProduto);
        boolean retornoBanco = ProdutoDAO.salvar(objCadastrar);
        
        if(retornoBanco){
            JOptionPane.showMessageDialog(rootPane, "Produto Cadastrado com sucesso!");
                txtNomeProdutoCadastro.setText("");
                txtCodigoProdutoCadastro.setText("");
                txtValorProdutoCadastro.setText("");
                txtQtdProdutoCadastro.setText("");
                lblIDProduto.setText("");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrar produto!");
        }
        }
    }//GEN-LAST:event_btnConfirmarCadastroProdutoActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        
    }//GEN-LAST:event_txtNomeProdutoActionPerformed
    public void atualizarTabela(){
            ArrayList<Produto> lista = ProdutoDAO.listar();
            DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
            modeloTabela.setRowCount(0);
            for (Produto item : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(item.getIdProduto()),
                    String.valueOf(item.getCodProduto()),
                    item.getNomeProduto(),
                    String.valueOf(item.getValorProduto()),
                    String.valueOf(item.getQtdProduto()),
                });
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelarCadastroProduto;
    private javax.swing.JButton btnConfirmarCadastroProduto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDProduto;
    private javax.swing.JPanel pnlCadastroProduto;
    private javax.swing.JPanel pnlConsultaProduto;
    private javax.swing.JTabbedPane pnlGuiasProduto;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodigoProdutoCadastro;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeProdutoCadastro;
    private javax.swing.JTextField txtQtdProdutoCadastro;
    private javax.swing.JTextField txtValorProdutoCadastro;
    // End of variables declaration//GEN-END:variables
}
