/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto.views;

import com.mycompany.projeto.dao.ClienteDAO;
import com.mycompany.projeto.models.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class TelaClientes extends javax.swing.JFrame {

    Cliente objAlterar = null;
    
    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGuiasCliente = new javax.swing.JTabbedPane();
        pnlCadastroCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCPFCadastro = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        lblIDCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JTextField();
        btnConfirmarCadastroCliente = new javax.swing.JButton();
        btnCancelarCadastroCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeConsultar = new javax.swing.JTextField();
        btnPesquisarNomeCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAdicionarCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF:");

        try {
            txtCPFCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFCadastroActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setText("Nome:");

        txtNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        txtEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCadastroActionPerformed(evt);
            }
        });

        btnConfirmarCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_sim.png"))); // NOI18N
        btnConfirmarCadastroCliente.setText("Confirmar");
        btnConfirmarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCadastroClienteActionPerformed(evt);
            }
        });

        btnCancelarCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_nao.png"))); // NOI18N
        btnCancelarCadastroCliente.setText("Cancelar");

        javax.swing.GroupLayout pnlCadastroClienteLayout = new javax.swing.GroupLayout(pnlCadastroCliente);
        pnlCadastroCliente.setLayout(pnlCadastroClienteLayout);
        pnlCadastroClienteLayout.setHorizontalGroup(
            pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                        .addComponent(btnConfirmarCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroClienteLayout.createSequentialGroup()
                        .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(280, 280, 280))
                    .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCadastroClienteLayout.setVerticalGroup(
            pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCadastroCliente)
                    .addComponent(btnCancelarCadastroCliente))
                .addContainerGap())
        );

        pnlGuiasCliente.addTab("Cadastrar", pnlCadastroCliente);

        jLabel5.setText("Nome:");

        txtNomeConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultarActionPerformed(evt);
            }
        });

        btnPesquisarNomeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_lupa.png"))); // NOI18N
        btnPesquisarNomeCliente.setText("Pesquisar");
        btnPesquisarNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_adicionar.png"))); // NOI18N
        btnAdicionarCliente.setText("Adicionar");
        btnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_lapis.png"))); // NOI18N
        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone_nao.png"))); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeConsultar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnAlterarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisarNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarNomeCliente))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdicionarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(btnExcluirCliente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlGuiasCliente.addTab("Consultar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastroActionPerformed

    private void txtCPFCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFCadastroActionPerformed

    private void txtEmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCadastroActionPerformed

    private void btnPesquisarNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeClienteActionPerformed
    String nomePesquisa = txtNomeConsultar.getText().trim();
    ArrayList<Cliente> lista = ClienteDAO.listar();
    DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
    modeloTabela.setRowCount(0);

    if (!nomePesquisa.isEmpty()) {
        boolean encontrou = false;
        for (Cliente item : lista) {
            if (item.getNomeCliente().toLowerCase().contains(nomePesquisa.toLowerCase())) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(item.getIdCliente()),
                    item.getCPF(),
                    item.getNomeCliente(),
                    item.getEmailCliente()
                });
                encontrou = true;
            }
        }
        if (!encontrou) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum cliente encontrado com o nome informado!");
        }
    } else {

        for (Cliente item : lista) {
            modeloTabela.addRow(new String[]{
                String.valueOf(item.getIdCliente()),
                item.getCPF(),
                item.getNomeCliente(),
                item.getEmailCliente()
            });
        }
    }
    }//GEN-LAST:event_btnPesquisarNomeClienteActionPerformed

    private void btnConfirmarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCadastroClienteActionPerformed
 
        if(objAlterar != null){
            String nome = txtNomeCadastro.getText();
            String email = txtEmailCadastro.getText();
            objAlterar.setNomeCliente(nome);
            objAlterar.setEmailCliente(email);
            boolean retornoAlteracao = ClienteDAO.alterar(objAlterar);
            if(retornoAlteracao){
                JOptionPane.showMessageDialog(rootPane, "Sucesso ao alterar");
                objAlterar = null;
                txtNomeCadastro.setText("");
                txtEmailCadastro.setText("");
                txtCPFCadastro.setText("");
                lblIDCliente.setText("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao alterar");
            }
        }else{
            String cpf = txtCPFCadastro.getText();
            String nome = txtNomeCadastro.getText();
            String email = txtEmailCadastro.getText();
        
        Cliente objCadastrar = new Cliente(nome, email, cpf);
        boolean retornoBanco = ClienteDAO.salvar(objCadastrar);
        
        if(retornoBanco){
            JOptionPane.showMessageDialog(rootPane, "Cliente Cadastrado com sucesso!");
                txtNomeCadastro.setText("");
                txtEmailCadastro.setText("");
                txtCPFCadastro.setText("");
                lblIDCliente.setText("");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrar usuário!");
        }
        }
    }//GEN-LAST:event_btnConfirmarCadastroClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        DefaultTableModel modeloClientes = (DefaultTableModel) tblClientes.getModel();
        int linhaSelecionada = tblClientes.getSelectedRow();
        if (linhaSelecionada >=0){
            int id = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 0).toString());
            String cpf = modeloClientes.getValueAt(linhaSelecionada, 1).toString();
            String nome = modeloClientes.getValueAt(linhaSelecionada, 2).toString();
            String email = modeloClientes.getValueAt(linhaSelecionada, 3).toString();
            
            objAlterar = new Cliente(id, nome, email, cpf);
            
            pnlGuiasCliente.setSelectedIndex(0);
            lblIDCliente.setText(String.valueOf(objAlterar.getIdCliente()));
            txtNomeCadastro.setText(objAlterar.getNomeCliente());
            txtCPFCadastro.setText(objAlterar.getCPF());
            txtEmailCadastro.setText(objAlterar.getEmailCliente());
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela!");
        }
        
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        int linhaSelecionada = tblClientes.getSelectedRow();
        if(linhaSelecionada>=0){
            DefaultTableModel modeloTabela = (DefaultTableModel)tblClientes.getModel();
            int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            boolean retorno = ClienteDAO.excluir(idExcluir);
            if(retorno){
                JOptionPane.showMessageDialog(rootPane, "Usuários deletado com sucesso!");
                atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não foi possível deletar o usuário!");
            }
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarClienteActionPerformed

    private void txtNomeConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultarActionPerformed
        
    }//GEN-LAST:event_txtNomeConsultarActionPerformed
    
    public void atualizarTabela(){
        ArrayList<Cliente> lista = ClienteDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
        modeloTabela.setRowCount(0);
        for (Cliente item : lista) {
            modeloTabela.addRow(new String[]{
                String.valueOf(item.getIdCliente()),
                item.getCPF(),
                item.getNomeCliente(),
                item.getEmailCliente()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCliente;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnCancelarCadastroCliente;
    private javax.swing.JButton btnConfirmarCadastroCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnPesquisarNomeCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JPanel pnlCadastroCliente;
    private javax.swing.JTabbedPane pnlGuiasCliente;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField txtCPFCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JTextField txtNomeConsultar;
    // End of variables declaration//GEN-END:variables
}
